/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.kay.document;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

/**
 *
 * @author sacklk
 */
public class Edit_Form_2 extends javax.swing.JPanel {

   /**
    * Creates new form Edit_Form_2
    * @param method
    */
   Method method ;
   public Edit_Form_2(Method method) 
   {
      
      initComponents();
  this.method = method;

  
     if(method!=null)
        
     {
        
      jTextPane1.setContentType("text/plain");
      jTextPane1.getDocument().addDocumentListener(new DocumentListener() { 

         @Override
         public void insertUpdate(DocumentEvent e) 
         {
            String html = jTextPane1.getText();
            jTextPane2.setContentType("text/html");
            jTextPane2.setText(html);
         }

         @Override
         public void removeUpdate(DocumentEvent e) 
         {
            String html = jTextPane1.getText();
            jTextPane2.setContentType("text/html");
            jTextPane2.setText(html);
         }

         @Override
         public void changedUpdate(DocumentEvent e)
         {
            String html = jTextPane1.getText();
            jTextPane2.setContentType("text/html");
            jTextPane2.setText(html);
         }
      });
      Document doc = Jsoup.parse(method.getMethod() +"\n\n"+ method.getParameters() +"\n\n"+  method.getDescription() +"\n\n"+  method.getPurpose() +"\n\n"+  method.getReturns()+"\n\n"+method.getExample()+"\n\n"+method.getNotes());
      String html = doc.outerHtml();
      jTextPane1.setText(html);
      
      jTextPane2.setContentType("text/html");
      jTextPane2.setText(html);
      
      
     }
      
      
      
      
      
   }

   /**
    * This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      jTextPane1 = new javax.swing.JTextPane();
      jButton2 = new javax.swing.JButton();
      jScrollPane2 = new javax.swing.JScrollPane();
      jTextPane2 = new javax.swing.JTextPane();
      htmlViewBtn = new javax.swing.JButton();
      jButton1 = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      jButton4 = new javax.swing.JButton();
      jButton5 = new javax.swing.JButton();
      jButton6 = new javax.swing.JButton();
      jButton7 = new javax.swing.JButton();

      jScrollPane1.setViewportView(jTextPane1);

      jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
      org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(Edit_Form_2.class, "Edit_Form_2.jButton2.text")); // NOI18N
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
         }
      });

      jTextPane2.setEditable(false);
      jScrollPane2.setViewportView(jTextPane2);

      org.openide.awt.Mnemonics.setLocalizedText(htmlViewBtn, org.openide.util.NbBundle.getMessage(Edit_Form_2.class, "Edit_Form_2.htmlViewBtn.text")); // NOI18N
      htmlViewBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            htmlViewBtnActionPerformed(evt);
         }
      });

      jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
      org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(Edit_Form_2.class, "Edit_Form_2.jButton1.text")); // NOI18N
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(jButton3, org.openide.util.NbBundle.getMessage(Edit_Form_2.class, "Edit_Form_2.jButton3.text")); // NOI18N
      jButton3.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(jButton4, org.openide.util.NbBundle.getMessage(Edit_Form_2.class, "Edit_Form_2.jButton4.text")); // NOI18N
      jButton4.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(jButton5, org.openide.util.NbBundle.getMessage(Edit_Form_2.class, "Edit_Form_2.jButton5.text")); // NOI18N
      jButton5.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(jButton6, org.openide.util.NbBundle.getMessage(Edit_Form_2.class, "Edit_Form_2.jButton6.text")); // NOI18N
      jButton6.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(jButton7, org.openide.util.NbBundle.getMessage(Edit_Form_2.class, "Edit_Form_2.jButton7.text")); // NOI18N
      jButton7.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton7ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jButton1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButton3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButton4)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButton5)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButton6)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButton7)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jButton2))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(htmlViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(14, 14, 14))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                     .addComponent(jScrollPane2)))
               .addGroup(layout.createSequentialGroup()
                  .addGap(227, 227, 227)
                  .addComponent(htmlViewBtn)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jButton2)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jButton1)
                  .addComponent(jButton3)
                  .addComponent(jButton4)
                  .addComponent(jButton5)
                  .addComponent(jButton6)
                  .addComponent(jButton7)))
            .addContainerGap(15, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void htmlViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htmlViewBtnActionPerformed
      
      jTextPane2.setText("");
      String html = jTextPane1.getText();
      jTextPane2.setContentType("text/html");
      jTextPane2.setText(html);
      
      
   }//GEN-LAST:event_htmlViewBtnActionPerformed

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

      //JOptionPane.showMessageDialog(jTextPane1, method.getMethod_ID());
      String HTML = jTextPane1.getText();
      Document doc = Jsoup.parse(HTML);
      
      Element meth = doc.getElementById("method");
      Element desc = doc.getElementById("desc");
      Element para = doc.getElementById("para");
      Element ret = doc.getElementById("ret");
      Element purp = doc.getElementById("purp");
      Element exmp = doc.getElementById("exmpl");
      Element notes = doc.getElementById("notes");

      
      Method method = new Method();
      
      
      if(meth!=null)
      method.setMethod(meth.outerHtml());
     
            if(desc!=null)
      method.setDescription(desc.outerHtml());
            
                  if(para!=null)
      method.setParameters(para.outerHtml());
                  
                        if(ret!=null)
      method.setReturns(ret.outerHtml());
                        
                              if(purp!=null)
      method.setPurpose(purp.outerHtml());
                              
                                    if(null!=exmp)
      method.setExample(exmp.outerHtml());
       
                                         if(null!=notes)
      method.setNotes(notes.outerHtml());
                                    
                                    
      
      DataHandler data = new DataHandler();
      boolean done =  data.updateMethod(this.method.getMethod_ID(), method);
      
      
     if(done)
     {
        JOptionPane.showMessageDialog(jTextPane1, "Document saved");
     }
     else
     {
        JOptionPane.showMessageDialog(jTextPane1, "Something went wrong. Check HTML");
     }
      
      
    

 
      
      
      
   }//GEN-LAST:event_jButton2ActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
      if(jTextPane1.getSelectedText()!=null)
      {
      jTextPane1.replaceSelection(new HTML_Editor().insertBold(jTextPane1.getSelectedText()));
      
      }
      
      else
      {
      
      JOptionPane.showMessageDialog(jTextPane1, "No text has been selected.");
      }
   }//GEN-LAST:event_jButton1ActionPerformed

   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  
  if(jTextPane1.getSelectedText()!=null)
  {
  jTextPane1.replaceSelection(new HTML_Editor().insertUnderline(jTextPane1.getSelectedText()));
  
  }
    else
      {
      
      JOptionPane.showMessageDialog(jTextPane1, "No text has been selected.");
      }
      
   }//GEN-LAST:event_jButton3ActionPerformed

   private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
      if(jTextPane1.getSelectedText()!=null)
      {
      Color initialcolor=Color.BLACK;    
      Color color  = JColorChooser.showDialog(this, "Select a color", initialcolor);
      String hexCol =  "#"+Integer.toHexString(color.getRGB()& 0x00ffffff);
   //   JOptionPane.showMessageDialog(jTextPane1, hexCol);
      jTextPane1.replaceSelection(new HTML_Editor().insertColor(jTextPane1.getSelectedText(), hexCol));
      
      }
      
     else
      {
      JOptionPane.showMessageDialog(jTextPane1, "No text has been selected.");
      } 
   }//GEN-LAST:event_jButton4ActionPerformed

   private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      
      jTextPane1.replaceSelection(new HTML_Editor().insertBreak());
      
      
   }//GEN-LAST:event_jButton5ActionPerformed

   private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     
      
            jTextPane1.replaceSelection(new HTML_Editor().insertParagraph());

      
      
   }//GEN-LAST:event_jButton6ActionPerformed

   private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      
      
                  jTextPane1.replaceSelection(new HTML_Editor().insertCode(jTextPane1.getSelectedText()));

      
      
      
   }//GEN-LAST:event_jButton7ActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton htmlViewBtn;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton5;
   private javax.swing.JButton jButton6;
   private javax.swing.JButton jButton7;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JTextPane jTextPane1;
   private javax.swing.JTextPane jTextPane2;
   // End of variables declaration//GEN-END:variables
}
